# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# integrate.py
# Created on: 2015-07-21 17:59:23.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
wwi_ortho_shp = "E:\\Hayden_Elza\\temp2\\wwi_ortho.shp"

# Process: Integrate
arcpy.Integrate_management("E:\\Hayden_Elza\\temp2\\wwi_ortho.shp #", "0.5 Meters")

